version: '3'

services:
  oracle-xe:
    container_name: oracle-xe
    image: 'oracle-xe:21.3.0'
    shm_size: '1gb'
    environment:
      TZ: Asia/Bangkok
      ORACLE_PWD: Pa55w0rd
      ORACLE_CHARACTERSET: TH8TISASCII
    ports:
      - '1521:1521'
      - '5500:5500'
    volumes:
      - oradata:/opt/oracle/oradata
volumes:
  oradata:
