version: '3.3'

services:
    OracleXE:
        container_name: OracleXE
        image: 'oracle/database:11.2.0.2-xe'
        shm_size: '1gb'
        ports:
            - '1521:1521'
            - '8081:8080'
        environment:
            - ORACLE_PWD=12345
        volumes:
            - ./data:/u01/app/oracle/oradata
